Code to load and reformat the current datasets given into a unified format. We have decided this to be

cid, label, features...

Note we write with index=False so we dont add the panadas deafult index column

In [1]:
import pandas as pd
import numpy as np

# Universe Sample 1 (background_url_tech_features)

In [2]:
background_url = pd.read_csv('../data/background_url.csv')
background_url.head()

   id  cid                              url  is_spam  has_financial
0   0    3            portcullisgates.co.uk        0              1
1   3    6               naturallymed.co.uk        0              1
2   5    9             nsconstruction.co.uk       -1              1
3   7   11  copplestoneprimaryschool.ik.org        1              1
4   9   16                hiddenideas.co.uk        0              1

In [3]:
tech_features = pd.read_csv('../data/background_url_tech_features.csv')
tech_features.head()

,Unnamed: 0,cid,source,label,url,cid/tech/ecommerce,url/tech/traffic_rank,url/tech/conversion_tracking,url/tech/html_ids,url/tech/html_classes,...,url/tech/platform_count,url/tech/subscribe,url/tech/univ_analytics,url/tech/tech_sum,url/tech/likes,url/tech/feedback,url/tech/analytics_count,url/tech/video_count,url/tech/mobile_aware,set_
0,237507,900500,background_url,0,bureauveritas.com,0,5.178894,0,1.863323,2.276462,...,3,0,0,1,3.831742,0,0,0,0,train
1,781027,2816195,background_url,0,pyruby.co.uk,0,6.796991,0,1.431364,2.025306,...,0,0,0,1,0.000000,0,0,0,0,train
2,758158,2713126,background_url,0,movency.co.uk,0,6.796991,0,0.000000,0.000000,...,0,0,0,0,0.000000,0,0,0,0,test
3,98960,310624,background_url,0,mlconsulting.co.uk,0,6.796991,0,0.000000,1.579784,...,0,0,0,1,0.000000,0,0,0,1,train
4,433287,1680008,background_url,0,archer-consulting.co.uk,0,6.796991,0,1.447158,1.973128,...,1,0,0,1,0.000000,0,0,0,0,train

In [4]:
tech_features.describe()

,Unnamed: 0,cid,label,cid/tech/ecommerce,url/tech/traffic_rank,url/tech/conversion_tracking,url/tech/html_ids,url/tech/html_classes,url/tech/login,url/tech/platform_count,url/tech/subscribe,url/tech/univ_analytics,url/tech/tech_sum,url/tech/likes,url/tech/feedback,url/tech/analytics_count,url/tech/video_count,url/tech/mobile_aware
count,909480.00000,909480.000000,909480,909480.000000,909480.000000,909480.000000,909480.000000,909480.000000,909480.000000,909480.000000,909480.000000,909480.000000,909480.000000,909480.000000,909480.000000,909480.000000,909480.000000,909480.000000
mean,454739.50000,1696266.596364,0,0.046376,6.753799,0.016050,0.704947,0.796207,0.167613,0.578400,0.051358,0.078383,0.416457,0.385266,0.001360,0.036302,0.036987,0.211653
std,262544.40575,997501.990968,0,0.210298,0.331560,0.196549,0.703596,0.796138,0.373523,1.194524,0.220727,0.268774,0.492971,1.028106,0.036855,0.204889,0.195563,0.479388
min,0.00000,3.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,227369.75000,877426.250000,0,0.000000,6.796991,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,454739.50000,1717001.500000,0,0.000000,6.796991,0.000000,0.698970,0.698970,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,682109.25000,2349451.250000,0,0.000000,6.796991,0.000000,1.322219,1.544068,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,909479.00000,4289281.000000,0,1.000000,7.406857,127.000000,3.741782,3.625827,1.000000,8.000000,1.000000,1.000000,1.000000,7.973324,1.000000,4.000000,3.000000,2.000000

In [5]:
tech_features_formatted = tech_features.drop(["Unnamed: 0", "source", "url", "set_"], axis=1)
tech_features_formatted.head()

,cid,label,cid/tech/ecommerce,url/tech/traffic_rank,url/tech/conversion_tracking,url/tech/html_ids,url/tech/html_classes,url/tech/login,url/tech/platform_count,url/tech/subscribe,url/tech/univ_analytics,url/tech/tech_sum,url/tech/likes,url/tech/feedback,url/tech/analytics_count,url/tech/video_count,url/tech/mobile_aware
0,900500,0,0,5.178894,0,1.863323,2.276462,0,3,0,0,1,3.831742,0,0,0,0
1,2816195,0,0,6.796991,0,1.431364,2.025306,1,0,0,0,1,0.000000,0,0,0,0
2,2713126,0,0,6.796991,0,0.000000,0.000000,0,0,0,0,0,0.000000,0,0,0,0
3,310624,0,0,6.796991,0,0.000000,1.579784,0,0,0,0,1,0.000000,0,0,0,1
4,1680008,0,0,6.796991,0,1.447158,1.973128,0,1,0,0,1,0.000000,0,0,0,0

In [6]:
tech_features_formatted.columns

Index([u'cid', u'label', u'cid/tech/ecommerce', u'url/tech/traffic_rank',
       u'url/tech/conversion_tracking', u'url/tech/html_ids',
       u'url/tech/html_classes', u'url/tech/login', u'url/tech/platform_count',
       u'url/tech/subscribe', u'url/tech/univ_analytics', u'url/tech/tech_sum',
       u'url/tech/likes', u'url/tech/feedback', u'url/tech/analytics_count',
       u'url/tech/video_count', u'url/tech/mobile_aware'],
      dtype='object')

In [7]:
tech_features_formatted.to_csv("../data/background_url_tech_features_formatted.csv", index=False)

# Small Labeled Sample (test_data.csv)

In [8]:
test_data_1 = pd.read_csv('../data/test_data.csv')
test_data_1.head()

,Unnamed: 0,added__orig_index,cid,label,cid/tech/ecommerce,url/tech/traffic_rank,url/tech/conversion_tracking,url/tech/html_ids,url/tech/html_classes,url/tech/login,url/tech/platform_count,url/tech/subscribe,url/tech/univ_analytics,url/tech/tech_sum,url/tech/likes,url/tech/feedback,url/tech/analytics_count,url/tech/video_count,url/tech/mobile_aware
0,0,1,899001,1,1,4.550876,0,1.672098,2.296665,1,6,1,0,1,5.264343,0,1,0,0
1,1,3,1703999,1,0,7.154740,0,0.477121,1.204120,0,0,0,0,1,0.000000,0,0,0,0
2,2,4,2247971,1,0,6.422567,0,2.053078,1.477121,1,0,0,0,0,0.000000,0,1,0,0
3,3,5,308163,1,0,6.796991,0,0.000000,0.000000,0,0,0,0,0,0.000000,0,0,0,0
4,4,6,1935839,1,0,6.796991,0,1.000000,1.000000,0,0,0,0,0,0.000000,0,0,0,0

In [9]:
test_data_1.describe()

,Unnamed: 0,added__orig_index,cid,label,cid/tech/ecommerce,url/tech/traffic_rank,url/tech/conversion_tracking,url/tech/html_ids,url/tech/html_classes,url/tech/login,url/tech/platform_count,url/tech/subscribe,url/tech/univ_analytics,url/tech/tech_sum,url/tech/likes,url/tech/feedback,url/tech/analytics_count,url/tech/video_count,url/tech/mobile_aware
count,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000,4311.000000
mean,2155.000000,9386.961726,1506337.963118,0.158664,0.178149,6.589576,0.047089,1.222470,1.474927,0.527256,2.178613,0.223614,0.198562,0.773370,1.480287,0.003248,0.101369,0.131292,0.508699
std,1244.622834,5385.596134,767799.022613,0.365405,0.382682,0.486168,0.220441,0.641616,0.713691,0.499314,1.745958,0.416715,0.398964,0.418699,1.545761,0.056901,0.321215,0.362285,0.656826
min,0.000000,1.000000,66.000000,0.000000,0.000000,2.346353,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1077.500000,4907.000000,901818.500000,0.000000,0.000000,6.401604,0.000000,0.954243,1.204120,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2155.000000,8475.000000,1642784.000000,0.000000,0.000000,6.796991,0.000000,1.380211,1.698970,1.000000,2.000000,0.000000,0.000000,1.000000,1.447158,0.000000,0.000000,0.000000,0.000000
75%,3232.500000,14429.500000,1956912.000000,0.000000,0.000000,6.796991,0.000000,1.672098,1.982271,1.000000,3.000000,0.000000,0.000000,1.000000,2.793430,0.000000,0.000000,0.000000,1.000000
max,4310.000000,20452.000000,4156878.000000,1.000000,1.000000,7.376553,2.000000,3.000434,2.848189,1.000000,8.000000,1.000000,1.000000,1.000000,6.883299,1.000000,3.000000,2.000000,2.000000

In [10]:
test_data_1_formatted = test_data_1.drop(["Unnamed: 0", "added__orig_index"], axis=1)
test_data_1_formatted.head()

,cid,label,cid/tech/ecommerce,url/tech/traffic_rank,url/tech/conversion_tracking,url/tech/html_ids,url/tech/html_classes,url/tech/login,url/tech/platform_count,url/tech/subscribe,url/tech/univ_analytics,url/tech/tech_sum,url/tech/likes,url/tech/feedback,url/tech/analytics_count,url/tech/video_count,url/tech/mobile_aware
0,899001,1,1,4.550876,0,1.672098,2.296665,1,6,1,0,1,5.264343,0,1,0,0
1,1703999,1,0,7.154740,0,0.477121,1.204120,0,0,0,0,1,0.000000,0,0,0,0
2,2247971,1,0,6.422567,0,2.053078,1.477121,1,0,0,0,0,0.000000,0,1,0,0
3,308163,1,0,6.796991,0,0.000000,0.000000,0,0,0,0,0,0.000000,0,0,0,0
4,1935839,1,0,6.796991,0,1.000000,1.000000,0,0,0,0,0,0.000000,0,0,0,0

In [11]:
test_data_1_formatted.to_csv("../data/test_data_formatted.csv", index=False)

# Joining the Datasets

We have positives, alot of unlabeled and some negatives, with overlap. We need to combine the two. We now have 3 labels which we choose to label

* 1 - positive
* 0 - unlabeled
* -1 - negative

The negative data is just to be used for the test set. We also have overlapping (but not perfectly) data frames. As a result we choose to join the two dataframes, then drop the duplicates from the universe.

In [12]:
features_cids = list(tech_features_formatted["cid"])
for cid in test_data_1_formatted["cid"]:
    if not cid in features_cids:
        print 'Not a perfect overlap, first missing cid is ', cid
        break

Not a perfect overlap, first missing cid is  532129.0

In [13]:
td1_f = test_data_1_formatted
uni_f = tech_features_formatted

td1_f.loc[td1_f.label==0,'label']=-1  # set negatives to -1 (0 is unlabeled now)

In [14]:
td1_uni = td1_f.append(uni_f, ignore_index=True)
td1_uni.describe()

,cid,label,cid/tech/ecommerce,url/tech/traffic_rank,url/tech/conversion_tracking,url/tech/html_ids,url/tech/html_classes,url/tech/login,url/tech/platform_count,url/tech/subscribe,url/tech/univ_analytics,url/tech/tech_sum,url/tech/likes,url/tech/feedback,url/tech/analytics_count,url/tech/video_count,url/tech/mobile_aware
count,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000,913791.000000
mean,1695370.568347,-0.003221,0.046998,6.753024,0.016196,0.707388,0.799409,0.169310,0.585949,0.052171,0.078950,0.418140,0.390432,0.001369,0.036609,0.037432,0.213054
std,996627.285703,0.068610,0.211634,0.332648,0.196680,0.704210,0.797127,0.375026,1.202729,0.222371,0.269661,0.493254,1.033884,0.036975,0.205640,0.196787,0.480810
min,3.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,877752.000000,0.000000,0.000000,6.796991,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1716557.000000,0.000000,0.000000,6.796991,0.000000,0.698970,0.698970,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2346645.500000,0.000000,0.000000,6.796991,0.000000,1.322219,1.544068,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,4289281.000000,1.000000,1.000000,7.406857,127.000000,3.741782,3.625827,1.000000,8.000000,1.000000,1.000000,1.000000,7.973324,1.000000,4.000000,3.000000,2.000000

And now we need to drop the duplicates

In [15]:
td1_uni_f = td1_uni.drop_duplicates('cid')
td1_uni_f.describe()

,cid,label,cid/tech/ecommerce,url/tech/traffic_rank,url/tech/conversion_tracking,url/tech/html_ids,url/tech/html_classes,url/tech/login,url/tech/platform_count,url/tech/subscribe,url/tech/univ_analytics,url/tech/tech_sum,url/tech/likes,url/tech/feedback,url/tech/analytics_count,url/tech/video_count,url/tech/mobile_aware
count,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000,909495.000000
mean,1696254.783314,-0.003236,0.046376,6.753796,0.016050,0.704951,0.796215,0.167617,0.578420,0.051359,0.078383,0.416460,0.385278,0.001360,0.036306,0.036989,0.211666
std,997505.191129,0.068772,0.210299,0.331563,0.196548,0.703598,0.796143,0.373526,1.194542,0.220730,0.268774,0.492972,1.028116,0.036854,0.204897,0.195566,0.479409
min,3.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,877386.500000,0.000000,0.000000,6.796991,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1716996.000000,0.000000,0.000000,6.796991,0.000000,0.698970,0.698970,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2349450.000000,0.000000,0.000000,6.796991,0.000000,1.322219,1.544068,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,4289281.000000,1.000000,1.000000,7.406857,127.000000,3.741782,3.625827,1.000000,8.000000,1.000000,1.000000,1.000000,7.973324,1.000000,4.000000,3.000000,2.000000

In [16]:
# check we havent lost anything
td1_pos = len(td1_f[td1_f['label'] == 1])
td1_neg = len(td1_f[td1_f['label'] == -1])
td1_uni_pos = len(td1_uni[td1_uni['label'] == 1])
td1_uni_neg = len(td1_uni[td1_uni['label'] == -1])

print td1_pos == td1_uni_pos
print td1_neg == td1_uni_neg

True
True

In [17]:
td1_uni_f.to_csv("../data/test1_uni_f.csv", index=False)