Code to load and reformat the current datasets given into a unified format. We have decided this to be

cid, label, features...

Note we write with index=False so we dont add the panadas deafult index column

In [1]:
import pandas as pd
import numpy as np

# Universe Sample 1 (background_url_tech_features)

In [2]:
background_url = pd.read_csv('../data/background_url.csv')
background_url.head()

   id  cid                              url  is_spam  has_financial
0   0    3            portcullisgates.co.uk        0              1
1   3    6               naturallymed.co.uk        0              1
2   5    9             nsconstruction.co.uk       -1              1
3   7   11  copplestoneprimaryschool.ik.org        1              1
4   9   16                hiddenideas.co.uk        0              1

In [3]:
tech_features = pd.read_csv('../data/background_url_tech_features.csv')
tech_features.head()

,Unnamed: 0,cid,source,label,url,cid/tech/ecommerce,url/tech/traffic_rank,url/tech/conversion_tracking,url/tech/html_ids,url/tech/html_classes,...,url/tech/platform_count,url/tech/subscribe,url/tech/univ_analytics,url/tech/tech_sum,url/tech/likes,url/tech/feedback,url/tech/analytics_count,url/tech/video_count,url/tech/mobile_aware,set_
0,237507,900500,background_url,0,bureauveritas.com,0,5.178894,0,1.863323,2.276462,...,3,0,0,1,3.831742,0,0,0,0,train
1,781027,2816195,background_url,0,pyruby.co.uk,0,6.796991,0,1.431364,2.025306,...,0,0,0,1,0.000000,0,0,0,0,train
2,758158,2713126,background_url,0,movency.co.uk,0,6.796991,0,0.000000,0.000000,...,0,0,0,0,0.000000,0,0,0,0,test
3,98960,310624,background_url,0,mlconsulting.co.uk,0,6.796991,0,0.000000,1.579784,...,0,0,0,1,0.000000,0,0,0,1,train
4,433287,1680008,background_url,0,archer-consulting.co.uk,0,6.796991,0,1.447158,1.973128,...,1,0,0,1,0.000000,0,0,0,0,train

In [4]:
tech_features.columns

Index([u'Unnamed: 0', u'cid', u'source', u'label', u'url',
       u'cid/tech/ecommerce', u'url/tech/traffic_rank',
       u'url/tech/conversion_tracking', u'url/tech/html_ids',
       u'url/tech/html_classes', u'url/tech/login', u'url/tech/platform_count',
       u'url/tech/subscribe', u'url/tech/univ_analytics', u'url/tech/tech_sum',
       u'url/tech/likes', u'url/tech/feedback', u'url/tech/analytics_count',
       u'url/tech/video_count', u'url/tech/mobile_aware', u'set_'],
      dtype='object')

In [5]:
tech_features_formatted = tech_features.drop(["Unnamed: 0", "source", "url", "set_"], axis=1)
tech_features_formatted.head()

,cid,label,cid/tech/ecommerce,url/tech/traffic_rank,url/tech/conversion_tracking,url/tech/html_ids,url/tech/html_classes,url/tech/login,url/tech/platform_count,url/tech/subscribe,url/tech/univ_analytics,url/tech/tech_sum,url/tech/likes,url/tech/feedback,url/tech/analytics_count,url/tech/video_count,url/tech/mobile_aware
0,900500,0,0,5.178894,0,1.863323,2.276462,0,3,0,0,1,3.831742,0,0,0,0
1,2816195,0,0,6.796991,0,1.431364,2.025306,1,0,0,0,1,0.000000,0,0,0,0
2,2713126,0,0,6.796991,0,0.000000,0.000000,0,0,0,0,0,0.000000,0,0,0,0
3,310624,0,0,6.796991,0,0.000000,1.579784,0,0,0,0,1,0.000000,0,0,0,1
4,1680008,0,0,6.796991,0,1.447158,1.973128,0,1,0,0,1,0.000000,0,0,0,0

In [6]:
tech_features_formatted.columns

Index([u'cid', u'label', u'cid/tech/ecommerce', u'url/tech/traffic_rank',
       u'url/tech/conversion_tracking', u'url/tech/html_ids',
       u'url/tech/html_classes', u'url/tech/login', u'url/tech/platform_count',
       u'url/tech/subscribe', u'url/tech/univ_analytics', u'url/tech/tech_sum',
       u'url/tech/likes', u'url/tech/feedback', u'url/tech/analytics_count',
       u'url/tech/video_count', u'url/tech/mobile_aware'],
      dtype='object')

In [7]:
tech_features_formatted.to_csv("../data/background_url_tech_features_formatted.csv", index=False)

# Small Labeled Sample (test_data.csv)

In [8]:
test_data_1 = pd.read_csv('../data/test_data.csv')
test_data_1.head()

,Unnamed: 0,added__orig_index,cid,label,cid/tech/ecommerce,url/tech/traffic_rank,url/tech/conversion_tracking,url/tech/html_ids,url/tech/html_classes,url/tech/login,url/tech/platform_count,url/tech/subscribe,url/tech/univ_analytics,url/tech/tech_sum,url/tech/likes,url/tech/feedback,url/tech/analytics_count,url/tech/video_count,url/tech/mobile_aware
0,0,1,899001,1,1,4.550876,0,1.672098,2.296665,1,6,1,0,1,5.264343,0,1,0,0
1,1,3,1703999,1,0,7.154740,0,0.477121,1.204120,0,0,0,0,1,0.000000,0,0,0,0
2,2,4,2247971,1,0,6.422567,0,2.053078,1.477121,1,0,0,0,0,0.000000,0,1,0,0
3,3,5,308163,1,0,6.796991,0,0.000000,0.000000,0,0,0,0,0,0.000000,0,0,0,0
4,4,6,1935839,1,0,6.796991,0,1.000000,1.000000,0,0,0,0,0,0.000000,0,0,0,0

In [9]:
test_data_1.columns

Index([u'Unnamed: 0', u'added__orig_index', u'cid', u'label',
       u'cid/tech/ecommerce', u'url/tech/traffic_rank',
       u'url/tech/conversion_tracking', u'url/tech/html_ids',
       u'url/tech/html_classes', u'url/tech/login', u'url/tech/platform_count',
       u'url/tech/subscribe', u'url/tech/univ_analytics', u'url/tech/tech_sum',
       u'url/tech/likes', u'url/tech/feedback', u'url/tech/analytics_count',
       u'url/tech/video_count', u'url/tech/mobile_aware'],
      dtype='object')

In [10]:
test_data_1_formatted = test_data_1.drop(["Unnamed: 0", "added__orig_index"], axis=1)
test_data_1_formatted.head()

,cid,label,cid/tech/ecommerce,url/tech/traffic_rank,url/tech/conversion_tracking,url/tech/html_ids,url/tech/html_classes,url/tech/login,url/tech/platform_count,url/tech/subscribe,url/tech/univ_analytics,url/tech/tech_sum,url/tech/likes,url/tech/feedback,url/tech/analytics_count,url/tech/video_count,url/tech/mobile_aware
0,899001,1,1,4.550876,0,1.672098,2.296665,1,6,1,0,1,5.264343,0,1,0,0
1,1703999,1,0,7.154740,0,0.477121,1.204120,0,0,0,0,1,0.000000,0,0,0,0
2,2247971,1,0,6.422567,0,2.053078,1.477121,1,0,0,0,0,0.000000,0,1,0,0
3,308163,1,0,6.796991,0,0.000000,0.000000,0,0,0,0,0,0.000000,0,0,0,0
4,1935839,1,0,6.796991,0,1.000000,1.000000,0,0,0,0,0,0.000000,0,0,0,0

In [11]:
test_data_1_formatted.to_csv("../data/test_data_formatted.csv", index=False)